#!/bin/bash
pom=1;
break_time=5;
pomo_time=15;
t=$pomo_time;
m=60
breaking=0;
on_task=1;
while :;
do
  if [ $breaking -eq 1 ]
  then
    for i in {0..1};
    do
      printf '\7';
      sleep 0.1;
    done;
    xmessage -buttons work,quit "get back to work."
    work=$?
    if [ $work -eq 101 ]
    then
      if [ $on_task -eq 1 ]
      then
        ((pom++));
        python3 incr_goal.py pomodoro 1 `date +"%H:%M"`;
      fi
      t=$pomo_time
      breaking=0
      on_task=1
    else
      exit 1
    fi
  else
    printf "\n(pom #%d) %s starting at %s" "$pom" `[ $t -eq $pomo_time ] && echo "session" || echo "break"` `date +"%H:%M"`;
    for i in {0..2};
    do
      printf '\7';
      sleep 0.1;
    done;

    rando=$(( $RANDOM % 100 +1 ))
    if [[ $t -eq $pomo_time && rando -lt 40 ]]
    then
      rando=$(( $RANDOM % ( $t * 2 / 4 ) + ( $t / 4 ) ))
      sleep $(($rando*$m));

      for i in {0..1};
      do
        printf '\7';
        sleep 0.1;
      done;
      xmessage -buttons no,yes -timeout 30 "are you distracted? remember: if you lie, your life will not get better."
      if [ $? -eq 102 ]
      then
        t=$break_time
        on_task=0
      else
        sleep $(( ( $t - $rando ) * $m ))
      fi
    else
      sleep $(($t*$m));
    fi

    if [ $t -eq $break_time ]
    then
      breaking=1
    else
      for i in {0..1};
      do
        printf '\7';
        sleep 0.1;
      done;
      xmessage -buttons no,break -timeout 7 "take a break."
      if [ $? -eq 102 ]
      then
        t=$break_time
      else
        ((pom++));
        python3 incr_goal.py pomodoro 1 `date +"%H:%M"`;
        t=$pomo_time
      fi
    fi
  fi
done
